### ISSUE TITLE
Not a valid module

### ISSUE THREAD

**Issue by Sukadia** [kitsunies/emoji.lua#1]
Hi, I wanted to try out the module but my script for the life of me wouldn't see it.

I'm not the most talented in lua, but here's how I fixed it:
```lua
--First two lines of code
local emojis = {...} --Changed 'emoji' to 'emojis'
local emoji = {} --Added new line for module
```

Felt like a pull request would've been a bit overkill, but thought I'd at least mention it and not just leave it be.

**Comment by kitsunies** [comment]
I'm super sorry for the late response! 🙏

The module has been updated and now uses two separate files (again) so you can actually view it. 👀
